name: Build ShinnThieuu Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Prepare Package Structure
      run: |
        # 1. Tạo cấu trúc thư mục ứng dụng gốc
        mkdir -p ShinnThieuu_Output/Payload/FreeFire.app/Data/Managed/
        
        # 2. Đưa các tệp tài nguyên vào cấu trúc
        cp Assembly-CSharp-patch.bytes ShinnThieuu_Output/Payload/FreeFire.app/Data/Managed/
        cp localConfig.json ShinnThieuu_Output/Payload/FreeFire.app/
        
        echo "[+] Đã nạp thành công cấu hình ShinnThieuu Core v2.0"

    - name: Compile IPA
      run: |
        # 3. Di chuyển vào thư mục Output và nén Payload thành tệp IPA hoàn chỉnh
        cd ShinnThieuu_Output
        zip -r -y ../FreeFire_ShinnThieuu.ipa Payload/
        cd ..
        
        # Tạo một thư mục riêng chỉ để chứa tệp IPA thành phẩm giúp upload không bị rời rạc
        mkdir IPA_Release
        mv FreeFire_ShinnThieuu.ipa IPA_Release/

    - name: Upload Artifact IPA
      uses: actions/upload-artifact@v4
      with:
        name: ShinnThieuu_Release_IPA
        path: IPA_Release/FreeFire_ShinnThieuu.ipa
